package com.qdu.pojo;
// Generated 2019-4-9 19:55:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Agency generated by hbm2java
 */
public class Agency  implements java.io.Serializable {


     private Integer agencyId;
     private String agencyName;
     private String agencyContact;
     private int agencyScore;
     private String agencyContent;
     private Set routes = new HashSet(0);

    public Agency() {
    }

	
    public Agency(String agencyName, String agencyContact, int agencyScore, String agencyContent) {
        this.agencyName = agencyName;
        this.agencyContact = agencyContact;
        this.agencyScore = agencyScore;
        this.agencyContent = agencyContent;
    }
    public Agency(String agencyName, String agencyContact, int agencyScore, String agencyContent, Set routes) {
       this.agencyName = agencyName;
       this.agencyContact = agencyContact;
       this.agencyScore = agencyScore;
       this.agencyContent = agencyContent;
       this.routes = routes;
    }
   
    public Integer getAgencyId() {
        return this.agencyId;
    }
    
    public void setAgencyId(Integer agencyId) {
        this.agencyId = agencyId;
    }
    public String getAgencyName() {
        return this.agencyName;
    }
    
    public void setAgencyName(String agencyName) {
        this.agencyName = agencyName;
    }
    public String getAgencyContact() {
        return this.agencyContact;
    }
    
    public void setAgencyContact(String agencyContact) {
        this.agencyContact = agencyContact;
    }
    public int getAgencyScore() {
        return this.agencyScore;
    }
    
    public void setAgencyScore(int agencyScore) {
        this.agencyScore = agencyScore;
    }
    public String getAgencyContent() {
        return this.agencyContent;
    }
    
    public void setAgencyContent(String agencyContent) {
        this.agencyContent = agencyContent;
    }
    public Set getRoutes() {
        return this.routes;
    }
    
    public void setRoutes(Set routes) {
        this.routes = routes;
    }




}


