package com.qdu.pojo;
// Generated 2019-4-9 19:55:57 by Hibernate Tools 4.3.1



/**
 * Apply generated by hbm2java
 */
public class Apply  implements java.io.Serializable {


     private int applyId;
     private Group group;
     private Userinfo userinfo;
     private String contact;
     private String gstate;

    public Apply() {
    }

	
    public Apply(int applyId, Group group, Userinfo userinfo, String contact) {
        this.applyId = applyId;
        this.group = group;
        this.userinfo = userinfo;
        this.contact = contact;
    }
    public Apply(int applyId, Group group, Userinfo userinfo, String contact, String gstate) {
       this.applyId = applyId;
       this.group = group;
       this.userinfo = userinfo;
       this.contact = contact;
       this.gstate = gstate;
    }
   
    public int getApplyId() {
        return this.applyId;
    }
    
    public void setApplyId(int applyId) {
        this.applyId = applyId;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getGstate() {
        return this.gstate;
    }
    
    public void setGstate(String gstate) {
        this.gstate = gstate;
    }




}


