package com.qdu.pojo;
// Generated 2019-4-18 21:40:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer fcategoryId;
     private String fcategoryName;
     private Set foodinfos = new HashSet(0);

    public Category() {
    }

	
    public Category(String fcategoryName) {
        this.fcategoryName = fcategoryName;
    }
    public Category(String fcategoryName, Set foodinfos) {
       this.fcategoryName = fcategoryName;
       this.foodinfos = foodinfos;
    }
   
    public Integer getFcategoryId() {
        return this.fcategoryId;
    }
    
    public void setFcategoryId(Integer fcategoryId) {
        this.fcategoryId = fcategoryId;
    }
    public String getFcategoryName() {
        return this.fcategoryName;
    }
    
    public void setFcategoryName(String fcategoryName) {
        this.fcategoryName = fcategoryName;
    }
    public Set getFoodinfos() {
        return this.foodinfos;
    }
    
    public void setFoodinfos(Set foodinfos) {
        this.foodinfos = foodinfos;
    }




}


