package com.qdu.pojo;
// Generated 2019-5-4 22:17:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Foodstore generated by hbm2java
 */
public class Foodstore  implements java.io.Serializable {


     private Integer did;
     private City city;
     private String dname;
     private String daddress;
     private Set foodinfos = new HashSet(0);

    public Foodstore() {
    }

	
    public Foodstore(City city, String dname, String daddress) {
        this.city = city;
        this.dname = dname;
        this.daddress = daddress;
    }
    public Foodstore(City city, String dname, String daddress, Set foodinfos) {
       this.city = city;
       this.dname = dname;
       this.daddress = daddress;
       this.foodinfos = foodinfos;
    }
   
    public Integer getDid() {
        return this.did;
    }
    
    public void setDid(Integer did) {
        this.did = did;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public String getDname() {
        return this.dname;
    }
    
    public void setDname(String dname) {
        this.dname = dname;
    }
    public String getDaddress() {
        return this.daddress;
    }
    
    public void setDaddress(String daddress) {
        this.daddress = daddress;
    }
    public Set getFoodinfos() {
        return this.foodinfos;
    }
    
    public void setFoodinfos(Set foodinfos) {
        this.foodinfos = foodinfos;
    }




}


