package com.qdu.pojo;
// Generated 2019-4-18 21:40:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Foodcomment generated by hbm2java
 */
public class Foodcomment  implements java.io.Serializable {


     private Integer fcommentId;
     private Foodinfo foodinfo;
     private Userinfo userinfo;
     private String fcommentContent;
     private int fcommentScore;
     private Date fcommentTime;

    public Foodcomment() {
    }

    public Foodcomment(Foodinfo foodinfo, Userinfo userinfo, String fcommentContent, int fcommentScore, Date fcommentTime) {
       this.foodinfo = foodinfo;
       this.userinfo = userinfo;
       this.fcommentContent = fcommentContent;
       this.fcommentScore = fcommentScore;
       this.fcommentTime = fcommentTime;
    }
   
    public Integer getFcommentId() {
        return this.fcommentId;
    }
    
    public void setFcommentId(Integer fcommentId) {
        this.fcommentId = fcommentId;
    }
    public Foodinfo getFoodinfo() {
        return this.foodinfo;
    }
    
    public void setFoodinfo(Foodinfo foodinfo) {
        this.foodinfo = foodinfo;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getFcommentContent() {
        return this.fcommentContent;
    }
    
    public void setFcommentContent(String fcommentContent) {
        this.fcommentContent = fcommentContent;
    }
    public int getFcommentScore() {
        return this.fcommentScore;
    }
    
    public void setFcommentScore(int fcommentScore) {
        this.fcommentScore = fcommentScore;
    }
    public Date getFcommentTime() {
        return this.fcommentTime;
    }
    
    public void setFcommentTime(Date fcommentTime) {
        this.fcommentTime = fcommentTime;
    }




}


