package com.qdu.pojo;
// Generated 2019-5-4 22:17:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Foodinfo generated by hbm2java
 */
public class Foodinfo  implements java.io.Serializable {


     private Integer fid;
     private Category category;
     private Foodstore foodstore;
     private String fname;
     private int fscore;
     private String fimage;
     private float fprice;
     private Set foodcomments = new HashSet(0);

    public Foodinfo() {
    }

	
    public Foodinfo(Category category, Foodstore foodstore, String fname, int fscore, float fprice) {
        this.category = category;
        this.foodstore = foodstore;
        this.fname = fname;
        this.fscore = fscore;
        this.fprice = fprice;
    }
    public Foodinfo(Category category, Foodstore foodstore, String fname, int fscore, String fimage, float fprice, Set foodcomments) {
       this.category = category;
       this.foodstore = foodstore;
       this.fname = fname;
       this.fscore = fscore;
       this.fimage = fimage;
       this.fprice = fprice;
       this.foodcomments = foodcomments;
    }
   
    public Integer getFid() {
        return this.fid;
    }
    
    public void setFid(Integer fid) {
        this.fid = fid;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Foodstore getFoodstore() {
        return this.foodstore;
    }
    
    public void setFoodstore(Foodstore foodstore) {
        this.foodstore = foodstore;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public int getFscore() {
        return this.fscore;
    }
    
    public void setFscore(int fscore) {
        this.fscore = fscore;
    }
    public String getFimage() {
        return this.fimage;
    }
    
    public void setFimage(String fimage) {
        this.fimage = fimage;
    }
    public float getFprice() {
        return this.fprice;
    }
    
    public void setFprice(float fprice) {
        this.fprice = fprice;
    }
    public Set getFoodcomments() {
        return this.foodcomments;
    }
    
    public void setFoodcomments(Set foodcomments) {
        this.foodcomments = foodcomments;
    }




}


