package com.qdu.pojo;
// Generated 2019-5-7 15:45:56 by Hibernate Tools 4.3.1


import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;
/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private Integer gid;
     private City city;
      @DateTimeFormat(pattern="yyyy-MM-dd")
     private Date gtime;
     private float gprice;
     private int gquatity;
      @DateTimeFormat(pattern="yyyy-MM-dd")
     private Date gendTime;
     private String gcontent;
     private String uid;
     private String contact;
     private Integer gstate;

    public Group() {
    }

	
    public Group(City city, Date gtime, float gprice, int gquatity, Date gendTime, String gcontent, String uid, String contact) {
        this.city = city;
        this.gtime = gtime;
        this.gprice = gprice;
        this.gquatity = gquatity;
        this.gendTime = gendTime;
        this.gcontent = gcontent;
        this.uid = uid;
        this.contact = contact;
    }
    public Group(City city, Date gtime, float gprice, int gquatity, Date gendTime, String gcontent, String uid, String contact, Integer gstate) {
       this.city = city;
       this.gtime = gtime;
       this.gprice = gprice;
       this.gquatity = gquatity;
       this.gendTime = gendTime;
       this.gcontent = gcontent;
       this.uid = uid;
       this.contact = contact;
       this.gstate = gstate;
    }
   
    public Integer getGid() {
        return this.gid;
    }
    
    public void setGid(Integer gid) {
        this.gid = gid;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public Date getGtime() {
        return this.gtime;
    }
    
    public void setGtime(Date gtime) {
        this.gtime = gtime;
    }
    public float getGprice() {
        return this.gprice;
    }
    
    public void setGprice(float gprice) {
        this.gprice = gprice;
    }
    public int getGquatity() {
        return this.gquatity;
    }
    
    public void setGquatity(int gquatity) {
        this.gquatity = gquatity;
    }
    public Date getGendTime() {
        return this.gendTime;
    }
    
    public void setGendTime(Date gendTime) {
        this.gendTime = gendTime;
    }
    public String getGcontent() {
        return this.gcontent;
    }
    
    public void setGcontent(String gcontent) {
        this.gcontent = gcontent;
    }
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public Integer getGstate() {
        return this.gstate;
    }
    
    public void setGstate(Integer gstate) {
        this.gstate = gstate;
    }




}


