package com.qdu.pojo;
// Generated 2019-4-9 19:55:57 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private Integer gid;
     private City city;
     private Date gtime;
     private float gprice;
     private int gquatity;
     private Date gendTime;
     private String gcontent;
     private Set applies = new HashSet(0);

    public Group() {
    }

	
    public Group(City city, Date gtime, float gprice, int gquatity, Date gendTime, String gcontent) {
        this.city = city;
        this.gtime = gtime;
        this.gprice = gprice;
        this.gquatity = gquatity;
        this.gendTime = gendTime;
        this.gcontent = gcontent;
    }
    public Group(City city, Date gtime, float gprice, int gquatity, Date gendTime, String gcontent, Set applies) {
       this.city = city;
       this.gtime = gtime;
       this.gprice = gprice;
       this.gquatity = gquatity;
       this.gendTime = gendTime;
       this.gcontent = gcontent;
       this.applies = applies;
    }
   
    public Integer getGid() {
        return this.gid;
    }
    
    public void setGid(Integer gid) {
        this.gid = gid;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public Date getGtime() {
        return this.gtime;
    }
    
    public void setGtime(Date gtime) {
        this.gtime = gtime;
    }
    public float getGprice() {
        return this.gprice;
    }
    
    public void setGprice(float gprice) {
        this.gprice = gprice;
    }
    public int getGquatity() {
        return this.gquatity;
    }
    
    public void setGquatity(int gquatity) {
        this.gquatity = gquatity;
    }
    public Date getGendTime() {
        return this.gendTime;
    }
    
    public void setGendTime(Date gendTime) {
        this.gendTime = gendTime;
    }
    public String getGcontent() {
        return this.gcontent;
    }
    
    public void setGcontent(String gcontent) {
        this.gcontent = gcontent;
    }
    public Set getApplies() {
        return this.applies;
    }
    
    public void setApplies(Set applies) {
        this.applies = applies;
    }




}


