package com.qdu.pojo;
// Generated 2019-4-18 21:40:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Hotelcomment generated by hbm2java
 */
public class Hotelcomment  implements java.io.Serializable {


     private Integer hcommentId;
     private Hotel hotel;
     private Userinfo userinfo;
     private String hcommentContent;
     private int hcommentScore;
     private Date hcommentTime;

    public Hotelcomment() {
    }

    public Hotelcomment(Hotel hotel, Userinfo userinfo, String hcommentContent, int hcommentScore, Date hcommentTime) {
       this.hotel = hotel;
       this.userinfo = userinfo;
       this.hcommentContent = hcommentContent;
       this.hcommentScore = hcommentScore;
       this.hcommentTime = hcommentTime;
    }
   
    public Integer getHcommentId() {
        return this.hcommentId;
    }
    
    public void setHcommentId(Integer hcommentId) {
        this.hcommentId = hcommentId;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getHcommentContent() {
        return this.hcommentContent;
    }
    
    public void setHcommentContent(String hcommentContent) {
        this.hcommentContent = hcommentContent;
    }
    public int getHcommentScore() {
        return this.hcommentScore;
    }
    
    public void setHcommentScore(int hcommentScore) {
        this.hcommentScore = hcommentScore;
    }
    public Date getHcommentTime() {
        return this.hcommentTime;
    }
    
    public void setHcommentTime(Date hcommentTime) {
        this.hcommentTime = hcommentTime;
    }




}


