package com.qdu.pojo;
// Generated 2019-5-7 15:45:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hotel generated by hbm2java
 */
public class Hotel  implements java.io.Serializable {


     private Integer hotelId;
     private City city;
     private String hotelName;
     private float hotelPrice;
     private String hotelLevel;
     private int hotelScore;
     private String hotelImage;
     private Set layouts = new HashSet(0);
     private Set hotelorderses = new HashSet(0);
     private Set hotelcomments = new HashSet(0);

    public Hotel() {
    }

	
    public Hotel(City city, String hotelName, float hotelPrice, String hotelLevel, int hotelScore, String hotelImage) {
        this.city = city;
        this.hotelName = hotelName;
        this.hotelPrice = hotelPrice;
        this.hotelLevel = hotelLevel;
        this.hotelScore = hotelScore;
        this.hotelImage = hotelImage;
    }
    public Hotel(City city, String hotelName, float hotelPrice, String hotelLevel, int hotelScore, String hotelImage, Set layouts, Set hotelorderses, Set hotelcomments) {
       this.city = city;
       this.hotelName = hotelName;
       this.hotelPrice = hotelPrice;
       this.hotelLevel = hotelLevel;
       this.hotelScore = hotelScore;
       this.hotelImage = hotelImage;
       this.layouts = layouts;
       this.hotelorderses = hotelorderses;
       this.hotelcomments = hotelcomments;
    }
   
    public Integer getHotelId() {
        return this.hotelId;
    }
    
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public String getHotelName() {
        return this.hotelName;
    }
    
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }
    public float getHotelPrice() {
        return this.hotelPrice;
    }
    
    public void setHotelPrice(float hotelPrice) {
        this.hotelPrice = hotelPrice;
    }
    public String getHotelLevel() {
        return this.hotelLevel;
    }
    
    public void setHotelLevel(String hotelLevel) {
        this.hotelLevel = hotelLevel;
    }
    public int getHotelScore() {
        return this.hotelScore;
    }
    
    public void setHotelScore(int hotelScore) {
        this.hotelScore = hotelScore;
    }
    public String getHotelImage() {
        return this.hotelImage;
    }
    
    public void setHotelImage(String hotelImage) {
        this.hotelImage = hotelImage;
    }
    public Set getLayouts() {
        return this.layouts;
    }
    
    public void setLayouts(Set layouts) {
        this.layouts = layouts;
    }
    public Set getHotelorderses() {
        return this.hotelorderses;
    }
    
    public void setHotelorderses(Set hotelorderses) {
        this.hotelorderses = hotelorderses;
    }
    public Set getHotelcomments() {
        return this.hotelcomments;
    }
    
    public void setHotelcomments(Set hotelcomments) {
        this.hotelcomments = hotelcomments;
    }




}


