package com.qdu.pojo;
// Generated 2019-4-9 19:55:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Hotelcomment generated by hbm2java
 */
public class Hotelcomment  implements java.io.Serializable {


     private Integer hcommentId;
     private Userinfo userinfo;
     private int hotelId;
     private String hcommentContent;
     private int hcommentScore;
     private Date hcommentTime;

    public Hotelcomment() {
    }

    public Hotelcomment(Userinfo userinfo, int hotelId, String hcommentContent, int hcommentScore, Date hcommentTime) {
       this.userinfo = userinfo;
       this.hotelId = hotelId;
       this.hcommentContent = hcommentContent;
       this.hcommentScore = hcommentScore;
       this.hcommentTime = hcommentTime;
    }
   
    public Integer getHcommentId() {
        return this.hcommentId;
    }
    
    public void setHcommentId(Integer hcommentId) {
        this.hcommentId = hcommentId;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public int getHotelId() {
        return this.hotelId;
    }
    
    public void setHotelId(int hotelId) {
        this.hotelId = hotelId;
    }
    public String getHcommentContent() {
        return this.hcommentContent;
    }
    
    public void setHcommentContent(String hcommentContent) {
        this.hcommentContent = hcommentContent;
    }
    public int getHcommentScore() {
        return this.hcommentScore;
    }
    
    public void setHcommentScore(int hcommentScore) {
        this.hcommentScore = hcommentScore;
    }
    public Date getHcommentTime() {
        return this.hcommentTime;
    }
    
    public void setHcommentTime(Date hcommentTime) {
        this.hcommentTime = hcommentTime;
    }




}


