package com.qdu.pojo;
// Generated 2019-5-4 22:17:52 by Hibernate Tools 4.3.1



/**
 * LayoutId generated by hbm2java
 */
public class LayoutId  implements java.io.Serializable {


     private int hotelId;
     private float layoutPrice;
     private String layoutImage;
     private String layoutSize;
     private String layoutBed;

    public LayoutId() {
    }

	
    public LayoutId(int hotelId, float layoutPrice, String layoutSize, String layoutBed) {
        this.hotelId = hotelId;
        this.layoutPrice = layoutPrice;
        this.layoutSize = layoutSize;
        this.layoutBed = layoutBed;
    }
    public LayoutId(int hotelId, float layoutPrice, String layoutImage, String layoutSize, String layoutBed) {
       this.hotelId = hotelId;
       this.layoutPrice = layoutPrice;
       this.layoutImage = layoutImage;
       this.layoutSize = layoutSize;
       this.layoutBed = layoutBed;
    }
   
    public int getHotelId() {
        return this.hotelId;
    }
    
    public void setHotelId(int hotelId) {
        this.hotelId = hotelId;
    }
    public float getLayoutPrice() {
        return this.layoutPrice;
    }
    
    public void setLayoutPrice(float layoutPrice) {
        this.layoutPrice = layoutPrice;
    }
    public String getLayoutImage() {
        return this.layoutImage;
    }
    
    public void setLayoutImage(String layoutImage) {
        this.layoutImage = layoutImage;
    }
    public String getLayoutSize() {
        return this.layoutSize;
    }
    
    public void setLayoutSize(String layoutSize) {
        this.layoutSize = layoutSize;
    }
    public String getLayoutBed() {
        return this.layoutBed;
    }
    
    public void setLayoutBed(String layoutBed) {
        this.layoutBed = layoutBed;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LayoutId) ) return false;
		 LayoutId castOther = ( LayoutId ) other; 
         
		 return (this.getHotelId()==castOther.getHotelId())
 && (this.getLayoutPrice()==castOther.getLayoutPrice())
 && ( (this.getLayoutImage()==castOther.getLayoutImage()) || ( this.getLayoutImage()!=null && castOther.getLayoutImage()!=null && this.getLayoutImage().equals(castOther.getLayoutImage()) ) )
 && ( (this.getLayoutSize()==castOther.getLayoutSize()) || ( this.getLayoutSize()!=null && castOther.getLayoutSize()!=null && this.getLayoutSize().equals(castOther.getLayoutSize()) ) )
 && ( (this.getLayoutBed()==castOther.getLayoutBed()) || ( this.getLayoutBed()!=null && castOther.getLayoutBed()!=null && this.getLayoutBed().equals(castOther.getLayoutBed()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getHotelId();
         result = 37 * result + (int) this.getLayoutPrice();
         result = 37 * result + ( getLayoutImage() == null ? 0 : this.getLayoutImage().hashCode() );
         result = 37 * result + ( getLayoutSize() == null ? 0 : this.getLayoutSize().hashCode() );
         result = 37 * result + ( getLayoutBed() == null ? 0 : this.getLayoutBed().hashCode() );
         return result;
   }   


}


