package com.qdu.pojo;
// Generated 2019-5-4 22:17:52 by Hibernate Tools 4.3.1



/**
 * Report generated by hbm2java
 */
public class Report  implements java.io.Serializable {


     private Integer reportId;
     private Userinfo userinfo;
     private String reportContent;

    public Report() {
    }

    public Report(Userinfo userinfo, String reportContent) {
       this.userinfo = userinfo;
       this.reportContent = reportContent;
    }
   
    public Integer getReportId() {
        return this.reportId;
    }
    
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getReportContent() {
        return this.reportContent;
    }
    
    public void setReportContent(String reportContent) {
        this.reportContent = reportContent;
    }




}


