package com.qdu.pojo;
// Generated 2019-5-4 22:17:52 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;

/**
 * Routecomment generated by hbm2java
 */
public class Routecomment  implements java.io.Serializable {


     private Integer rcommentId;
     @JsonIgnore
     private City city;
     @JsonIgnore
     private Route route;
     @JsonIgnore
     private Userinfo userinfo;
     private String rcommentContent;
     private int rcommentScore;
     private Date rcommentTime;

    public Routecomment() {
    }

    public Routecomment(City city, Route route, Userinfo userinfo, String rcommentContent, int rcommentScore, Date rcommentTime) {
       this.city = city;
       this.route = route;
       this.userinfo = userinfo;
       this.rcommentContent = rcommentContent;
       this.rcommentScore = rcommentScore;
       this.rcommentTime = rcommentTime;
    }
   
    public Integer getRcommentId() {
        return this.rcommentId;
    }
    
    public void setRcommentId(Integer rcommentId) {
        this.rcommentId = rcommentId;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getRcommentContent() {
        return this.rcommentContent;
    }
    
    public void setRcommentContent(String rcommentContent) {
        this.rcommentContent = rcommentContent;
    }
    public int getRcommentScore() {
        return this.rcommentScore;
    }
    
    public void setRcommentScore(int rcommentScore) {
        this.rcommentScore = rcommentScore;
    }
    public Date getRcommentTime() {
        return this.rcommentTime;
    }
    
    public void setRcommentTime(Date rcommentTime) {
        this.rcommentTime = rcommentTime;
    }




}


