package com.qdu.pojo;
// Generated 2019-5-7 15:45:56 by Hibernate Tools 4.3.1



/**
 * Routeorders generated by hbm2java
 */
public class Routeorders  implements java.io.Serializable {


     private Integer routeOrderId;
     private String uid;
     private int routeId;
     private String routeName;
     private float routePrice;
     private String contact;
     private String routeOrderName;
     private int routeOrderPeople;

    public Routeorders() {
    }

    public Routeorders(String uid, int routeId, String routeName, float routePrice, String contact, String routeOrderName, int routeOrderPeople) {
       this.uid = uid;
       this.routeId = routeId;
       this.routeName = routeName;
       this.routePrice = routePrice;
       this.contact = contact;
       this.routeOrderName = routeOrderName;
       this.routeOrderPeople = routeOrderPeople;
    }
   
    public Integer getRouteOrderId() {
        return this.routeOrderId;
    }
    
    public void setRouteOrderId(Integer routeOrderId) {
        this.routeOrderId = routeOrderId;
    }
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    public int getRouteId() {
        return this.routeId;
    }
    
    public void setRouteId(int routeId) {
        this.routeId = routeId;
    }
    public String getRouteName() {
        return this.routeName;
    }
    
    public void setRouteName(String routeName) {
        this.routeName = routeName;
    }
    public float getRoutePrice() {
        return this.routePrice;
    }
    
    public void setRoutePrice(float routePrice) {
        this.routePrice = routePrice;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getRouteOrderName() {
        return this.routeOrderName;
    }
    
    public void setRouteOrderName(String routeOrderName) {
        this.routeOrderName = routeOrderName;
    }
    public int getRouteOrderPeople() {
        return this.routeOrderPeople;
    }
    
    public void setRouteOrderPeople(int routeOrderPeople) {
        this.routeOrderPeople = routeOrderPeople;
    }




}


