package com.qdu.pojo;
// Generated 2019-5-4 22:17:52 by Hibernate Tools 4.3.1



/**
 * Routeorders generated by hbm2java
 */
public class Routeorders  implements java.io.Serializable {


     private Integer routeOrderId;
     private Route routeByRouteId;
     private Route routeByRouteName;
     private Userinfo userinfo;
     private float routePrice;
     private String contact;
     private String routeOrderName;
     private int routeOrderPeople;

    public Routeorders() {
    }

    public Routeorders(Route routeByRouteId, Route routeByRouteName, Userinfo userinfo, float routePrice, String contact, String routeOrderName, int routeOrderPeople) {
       this.routeByRouteId = routeByRouteId;
       this.routeByRouteName = routeByRouteName;
       this.userinfo = userinfo;
       this.routePrice = routePrice;
       this.contact = contact;
       this.routeOrderName = routeOrderName;
       this.routeOrderPeople = routeOrderPeople;
    }
   
    public Integer getRouteOrderId() {
        return this.routeOrderId;
    }
    
    public void setRouteOrderId(Integer routeOrderId) {
        this.routeOrderId = routeOrderId;
    }
    public Route getRouteByRouteId() {
        return this.routeByRouteId;
    }
    
    public void setRouteByRouteId(Route routeByRouteId) {
        this.routeByRouteId = routeByRouteId;
    }
    public Route getRouteByRouteName() {
        return this.routeByRouteName;
    }
    
    public void setRouteByRouteName(Route routeByRouteName) {
        this.routeByRouteName = routeByRouteName;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public float getRoutePrice() {
        return this.routePrice;
    }
    
    public void setRoutePrice(float routePrice) {
        this.routePrice = routePrice;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getRouteOrderName() {
        return this.routeOrderName;
    }
    
    public void setRouteOrderName(String routeOrderName) {
        this.routeOrderName = routeOrderName;
    }
    public int getRouteOrderPeople() {
        return this.routeOrderPeople;
    }
    
    public void setRouteOrderPeople(int routeOrderPeople) {
        this.routeOrderPeople = routeOrderPeople;
    }




}


