package com.qdu.pojo;
// Generated 2019-5-7 15:45:56 by Hibernate Tools 4.3.1



/**
 * Scene generated by hbm2java
 */
public class Scene  implements java.io.Serializable {


     private Integer sceneId;
     private City city;
     private String sceneName;
     private String sceneImage;
     private Integer sceneScore;

    public Scene() {
    }

	
    public Scene(City city, String sceneName) {
        this.city = city;
        this.sceneName = sceneName;
    }
    public Scene(City city, String sceneName, String sceneImage, Integer sceneScore) {
       this.city = city;
       this.sceneName = sceneName;
       this.sceneImage = sceneImage;
       this.sceneScore = sceneScore;
    }
   
    public Integer getSceneId() {
        return this.sceneId;
    }
    
    public void setSceneId(Integer sceneId) {
        this.sceneId = sceneId;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public String getSceneName() {
        return this.sceneName;
    }
    
    public void setSceneName(String sceneName) {
        this.sceneName = sceneName;
    }
    public String getSceneImage() {
        return this.sceneImage;
    }
    
    public void setSceneImage(String sceneImage) {
        this.sceneImage = sceneImage;
    }
    public Integer getSceneScore() {
        return this.sceneScore;
    }
    
    public void setSceneScore(Integer sceneScore) {
        this.sceneScore = sceneScore;
    }




}


