package com.qdu.pojo;
// Generated 2019-4-9 19:55:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Userinfo generated by hbm2java
 */
public class Userinfo  implements java.io.Serializable {


     private String uid;
     private String ugender;
     private String ucity;
     private String ucontact;
     private String uemail;
     private String isBan;
     private String upassword;
     private int urank;
     private Set foodcomments = new HashSet(0);
     private Set essaycomments = new HashSet(0);
     private Set routeorderses = new HashSet(0);
     private Set applies = new HashSet(0);
     private Set routecomments = new HashSet(0);
     private Set hotelorderses = new HashSet(0);
     private Set messages = new HashSet(0);
     private Set essays = new HashSet(0);
     private Set reports = new HashSet(0);
     private Set hotelcomments = new HashSet(0);

    public Userinfo() {
    }

	
    public Userinfo(String uid, String ugender, String ucity, String ucontact, String uemail, String upassword, int urank) {
        this.uid = uid;
        this.ugender = ugender;
        this.ucity = ucity;
        this.ucontact = ucontact;
        this.uemail = uemail;
        this.upassword = upassword;
        this.urank = urank;
    }
    public Userinfo(String uid, String ugender, String ucity, String ucontact, String uemail, String isBan, String upassword, int urank, Set foodcomments, Set essaycomments, Set routeorderses, Set applies, Set routecomments, Set hotelorderses, Set messages, Set essays, Set reports, Set hotelcomments) {
       this.uid = uid;
       this.ugender = ugender;
       this.ucity = ucity;
       this.ucontact = ucontact;
       this.uemail = uemail;
       this.isBan = isBan;
       this.upassword = upassword;
       this.urank = urank;
       this.foodcomments = foodcomments;
       this.essaycomments = essaycomments;
       this.routeorderses = routeorderses;
       this.applies = applies;
       this.routecomments = routecomments;
       this.hotelorderses = hotelorderses;
       this.messages = messages;
       this.essays = essays;
       this.reports = reports;
       this.hotelcomments = hotelcomments;
    }
   
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    public String getUgender() {
        return this.ugender;
    }
    
    public void setUgender(String ugender) {
        this.ugender = ugender;
    }
    public String getUcity() {
        return this.ucity;
    }
    
    public void setUcity(String ucity) {
        this.ucity = ucity;
    }
    public String getUcontact() {
        return this.ucontact;
    }
    
    public void setUcontact(String ucontact) {
        this.ucontact = ucontact;
    }
    public String getUemail() {
        return this.uemail;
    }
    
    public void setUemail(String uemail) {
        this.uemail = uemail;
    }
    public String getIsBan() {
        return this.isBan;
    }
    
    public void setIsBan(String isBan) {
        this.isBan = isBan;
    }
    public String getUpassword() {
        return this.upassword;
    }
    
    public void setUpassword(String upassword) {
        this.upassword = upassword;
    }
    public int getUrank() {
        return this.urank;
    }
    
    public void setUrank(int urank) {
        this.urank = urank;
    }
    public Set getFoodcomments() {
        return this.foodcomments;
    }
    
    public void setFoodcomments(Set foodcomments) {
        this.foodcomments = foodcomments;
    }
    public Set getEssaycomments() {
        return this.essaycomments;
    }
    
    public void setEssaycomments(Set essaycomments) {
        this.essaycomments = essaycomments;
    }
    public Set getRouteorderses() {
        return this.routeorderses;
    }
    
    public void setRouteorderses(Set routeorderses) {
        this.routeorderses = routeorderses;
    }
    public Set getApplies() {
        return this.applies;
    }
    
    public void setApplies(Set applies) {
        this.applies = applies;
    }
    public Set getRoutecomments() {
        return this.routecomments;
    }
    
    public void setRoutecomments(Set routecomments) {
        this.routecomments = routecomments;
    }
    public Set getHotelorderses() {
        return this.hotelorderses;
    }
    
    public void setHotelorderses(Set hotelorderses) {
        this.hotelorderses = hotelorderses;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }
    public Set getEssays() {
        return this.essays;
    }
    
    public void setEssays(Set essays) {
        this.essays = essays;
    }
    public Set getReports() {
        return this.reports;
    }
    
    public void setReports(Set reports) {
        this.reports = reports;
    }
    public Set getHotelcomments() {
        return this.hotelcomments;
    }
    
    public void setHotelcomments(Set hotelcomments) {
        this.hotelcomments = hotelcomments;
    }




}


